language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install pandas
  - pip install pyarrow
# command to run tests
script:
  - python writingparquetfile.py
notifications:
  email:
    recipients:
      - yingtongm@163.com
    on_success: change
    on_failure: always
