language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
#install:
#  - pip install tox
# command to run tests
script:
  - python writingparquetfile.py
notifications:
  email:
    recipients:
      - yingtongm@163.com
    on_success: change
    on_failure: always
